name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      grep_tag:
        description: 'Cypress test tag (ör: regression, smoke, stage, prod)'
        required: true
        default: 'regression'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - 1-getting-started
          - 2-advanced-examples
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests for folder ${{ matrix.folder }}
        run: |
          npx cypress run \
            --spec "cypress/e2e/${{ matrix.folder }}/**/*.cy.js" \
            --env grepTags=${{ github.event.inputs.grep_tag }} \
            --config "videosFolder=cypress/videos-${{ matrix.folder }},screenshotsFolder=cypress/screenshots-${{ matrix.folder }}"

      - name: Upload video artifact for ${{ matrix.folder }}
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.folder }}
          path: cypress/videos-${{ matrix.folder }}
          retention-days: 5
          if-no-files-found: warn

      - name: Upload screenshot artifact for ${{ matrix.folder }}
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.folder }}
          path: cypress/screenshots-${{ matrix.folder }}
          retention-days: 5
          if-no-files-found: ignore

  merge-artifacts:
    needs: cypress-run
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all video artifacts
        uses: actions/download-artifact@v4
        with:
          path: merged-artifacts
          pattern: videos-*
          merge-multiple: true

      - name: Create merged videos directory
        run: mkdir -p all-videos

      - name: Merge all videos into one folder
        run: |
          find merged-artifacts -type f -name '*.mp4' -exec cp {} all-videos/ \;

      - name: Upload merged video artifact
        uses: actions/upload-artifact@v4
        with:
          name: all-cypress-videos
          path: all-videos
          retention-days: 5
          if-no-files-found: warn