name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      grep_tag:
        description: 'Cypress test tag (exp: regression, smoke, stage, prod)'
        required: true
        default: 'regression'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run Cypress tests with tag
        run: npx cypress run --env grepTags=${{ github.event.inputs.grep_tag }}